### ISSUE TITLE
Cannot Activate Module

### ISSUE THREAD

**Issue by Sarzo2112** [ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet#15]
I had the 5eOGLCharacterSheet installed and working fine. I upgraded Foundry to 7.6 and updated all my modules.  I had some errors, but didn't see what they were. When I launched Foundry the 5eCharacterSheet was no longer working and when I look in ManageModules I cannot find it in the list within Foundry.

I uninstalled all modules in SetUp and only installed the 5eCharacterSheet module and it still does not appear within ManageModules within Foundry.

Please help, I love the module and want to continue using it.
![ConfigureModules](https://user-images.githubusercontent.com/74395749/99032480-981ee780-2547-11eb-9f05-7148ae1814da.PNG)
![ManageModules](https://user-images.githubusercontent.com/74395749/99032488-9e14c880-2547-11eb-84a0-be7c3c991573.PNG)

**Comment by akrigline** [comment]
@Sarzo2112 thanks for the report, what version of the dnd5e system are you using?
The latest version of this sheet is only compatible with dnd5e 0.99 and I believe I set it up so that i cannot be activated without that being true (I'm not certain that's the issue here but it might be).

If you're unwilling to update you dnd5e system version, I'd recommend that you uninstall this sheet and reinstall version 0.4.2 manually with this module.json url:
```
https://github.com/ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet/releases/download/v0.4.2/module.json
```

**Comment by akrigline** [comment]
Going to close this as I believe the issue was the comment above.
